# Generated by Django 4.2.7 on 2024-04-23 12:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=datetime.datetime(2024, 4, 23, 12, 42, 55, 312179, tzinfo=datetime.timezone.utc), unique=True),
            preserve_default=False,
        ),
    ]
