# Generated by Django 5.0.4 on 2024-04-28 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_category_post_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='creation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
