# Generated by Django 4.2.7 on 2024-05-05 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_tag_alter_post_title_post_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tags',
            new_name='tag',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
    ]
