# Generated by Django 5.0.4 on 2024-04-26 06:50

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_alter_choice_question_alter_question_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='choice_slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
